### PR TITLE
Add spot dock and undock service

### PR DESCRIPTION
**Pull request by tkmtnt7000**
We add Spot dock station behavior.

Addition of rosservice
- Dock 
- Undock 

Cc: @k-okada

### CODE REVIEW

**Review by k-okada — COMMENTED** [review]
thank you, forget to add Dock.srv?

**Comment by tkmtnt7000** [comment]
Sorry, I forgot. I add it.

**Comment by mqcmd196** [comment]
Can the Spot identify his dock without any args in API?

**Comment by tkmtnt7000** [comment]
At least only `dock_id` (same as the april tag number) is necessary for identifying his dock in my understanding.

**Pull request merged**
