### PR TITLE
Update graphnav interfaces

### PR DESCRIPTION
**Pull request by sktometometo**
This PR is an example of rebased branch of develop/spot on master.

## Features

- Enable cancel interface of navigate_to action
- Split UploadGraph, SetLocalization services from navigate_to action
  + `~/upload_graph` (spot_msgs/UploadGraph)
  + `~/set_locallization_fiducial` (spot_msgs/SetLocalizationFiducial)
  + `~/set_localization_wapoint` (spot_msgs/SetLocalizationWaypoint)
- Add recording interfaces
  + `~/start_recording` (std_srvs/Trigger)
  + `~/stop_recording` (std_srvs/Trigger)
  + `~/download_graph` (spot_msgs/DownloadGraph)
  + `~/clear_graph` (spot_msgs/Trigger)

@tongtybj

### CODE REVIEW

**Comment by sktometometo** [comment]
Currently trajectory command seems not to work well.

**Comment by sktometometo** [comment]
There are still some bugs. But development will be pend until i am not busy.

**Comment by tongtybj** [comment]
> There are still some bugs

Is this because some changes in origin master branch?

**Comment by sktometometo** [comment]
I am not sure. I think i have made mistake when i have resolved confilicts.

**Comment by tongtybj** [comment]
If you don't have time, may I help you to finish this work. (at least https://github.com/clearpathrobotics/spot_ros/pull/41 solved the conflict by https://github.com/sktometometo/spot_ros/pull/9/commits/88bbdc801c63332d7d6658c3528f9744d3e15193).

**Pull request closed without merging**
